name: kh_s_application
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: ^3.6.0
dependencies: 
  flutter:   # 🚨 CRITICAL: Required for every Flutter project - DO NOT REMOVE
    sdk: flutter # 🚨 CRITICAL: Required for every Flutter project - DO NOT REMOVE
  flutter_localizations: 
    sdk: flutter
  flutter_svg: ^2.0.12
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.3
  connectivity_plus: ^6.1.0
  web: any
dev_dependencies: 
  flutter_test:    # 🚨 CRITICAL: Required for Flutter project testing - DO NOT REMOVE
    sdk: flutter    # 🚨 CRITICAL: Required for Flutter project testing - DO NOT REMOVE
flutter: 
  uses-material-design: true # 🚨 CRITICAL: Required for Material icon font - DO NOT REMOVE
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoRomanSemiBold.ttf
          weight: 600

  # 🚨 CRITICAL ASSET MANAGEMENT RULES:
  # - DO NOT ADD NEW ASSET DIRECTORIES (assets/svg/, assets/icons/, etc.)
  # - ONLY USE EXISTING AND ITEMS AVAILABLE IN THE DIRECTORIES LISTED ABOVE (assets/, assets/images/)

  # 🚨 CRITICAL FONTS RULE:
  # - DO NOT ADD NEW LOCAL FONTS TO assets/fonts/ 
  # - ONLY USE EXISTING LOCAL FONTS FROM assets/fonts/